- name: apt update
  apt:
    update_cache: yes

- name: Install figlet
  apt:
    name: figlet
    state: latest

- name: hidden default message
  shell: sudo chmod -x /etc/update-motd.d/*

- name: add message
  shell: sudo echo 'echo -e "\033[36m`figlet -f slant {{ project_name }} `\033[m"'>> .bash_profile