---
# tasks file for ufw

- name: ufw allow 22
  community.general.ufw:
    rule: allow
    port: '22'

- name: ufw allow 80
  community.general.ufw:
    rule: allow
    port: '80'

- name: ufw allow 3306
  community.general.ufw:
    rule: allow
    port: '3306'

- name: Enable firewall
  ufw:
    state: enabled

- name: "reload ufw"
  ufw:
    state: reloaded