---
# tasks file for php

- name: add-apt-repository ppa:ondrej/php
  # command: sudo add-apt-repository ppa:ondrej/php
  expect:
    command: sudo add-apt-repository ppa:ondrej/php
    responses:
      'Press': ''

- name: apt update
  apt:
    update_cache: yes

- name: Install PHP
  apt:
    name: php8.1
    state: latest

- name: Install PHP-xml
  apt:
    name: php8.1-xml
    state: latest

- name: Install PHP-fpm
  apt:
    name: php8.1-fpm
    state: latest

- name: Install PHP-mbstring
  apt:
    name: php-mbstring
    state: latest

- name: Install PHP-mysql
  apt:
    name: php-mysql
    state: latest

- name: Install PHP-curl
  apt:
    name: php-curl
    state: latest

# - name: Install php-pdo
#   apt:
#     name: php-pdo
#     state: latest

- name: replace php-fpm config
  copy:
    src: ../templates/_www.conf.j2
    dest: /etc/php/8.1/fpm/pool.d/www.conf